---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rubberduck-world
  namespace: minikube-demo
  labels:
    app: rubberduck
    env: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rubberduck
  template:
    metadata:
      labels:
        app: rubberduck
        tier: api
        env: staging
    spec:
      containers:
      - name: calert
        image: mrkaran/rubberduck:1.0.2
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "250m" # 250 milli cores
            memory: "160Mi"
          requests:
            cpu: "100m" # 150 milli cores
            memory: "70Mi"